### ISSUE TITLE
Can't view mail in quarantine 

### ISSUE THREAD

**Issue by maitayfox** [MailCleaner/MailCleaner#335]
Hi,

Since a week or two we are not able to view text of mail stuck in quarantine. 
When we click on the mail icon in the report a pop-up opens and it says "CANNOTLOAD HEADERANDBODY".

Any ideas ?

**Comment by JohnMertz** [comment]
Hello,

Sorry for the delay.

Ordinary usage questions are better submitted to forum.mailcleaner.net for discussion.

The error described here means that the quarantined file (stored in /var/mailcleaner/spam/) could not be fetched over the SOAP interface. Usually this is because the quarantined item has expired and been removed. However there are a number of other issues that could cause it. If it is an item stored on another node, it could be an inability to communicate between nodes. It could be an inability to communicate on the SOAP interface on the same node. The database reference with that Exim Queue ID may no longer exist, so it cannot determine where to locate the quarantined item (it is required to determine which recipient directory to look in), and so on.

If you or someone who is continuing to see this issue, the first thing to do would be to search the cluster to see if the file exists:

    $ command_to_cluster.sh "find /var/mailcleaner/spam -name EXIM_ID"

where EXIM_ID should be mentioned in the URL.

If it does not exist then that is the issue, if it does then it is some sort of SOAP interface or cluster configuration issue.

In the former case, check to see if other items are stored in that directory to ensure that there isn't a filesystem writing issue. If there are others, check to see the age of the message you are looking for. You should see the 'Automatic purge' duration in the bottom right of the user quarantine, but you can also find it with:

    echo 'select days_to_keep_spams from system_conf;' |  mc_mysql -m mc_config

There could be a number of other reasons that the message may not have expired, but could no longer exist, including manual deletion, unreadable filesystem, disappearance or change in host ID of the stored slave, etc.

The SOAP interface issue is less likely since you would have noticed a number of other issues. It is only really likely if the message is stored on a slave node. In which case you can try to verify HTTP access to that node via port 5132 (the custom SOAP port). It could be as simple as Apache being stopped on that node, or as complicated as an intricate networking issue.
