### ISSUE TITLE
Help in activating SSL (HTTPS)

### ISSUE THREAD

**Issue by joaomarcosmareto** [MailCleaner/MailCleaner#349]
Hello guys, good afternoon.

I just installed mailcleaner and made my tests. Everything was fine and fast until I checked the option for enabling SSL in the "Configuration > Services > Web Interfaces" page. After that, the system went crazy and became very slow.

Not only slow, but looking in the logs, I found the following messages:

May 27 10:40:14 localhost httpd: PHP Fatal error:  SOAP-ERROR: Parsing WSDL: Couldn't load from 'http://127.0.0.1:5132/soap/index.php?wsdl' : failed to load external entity "http://127.0.0.1:5132/soap/index.php?wsdl"#012 in /usr/mailcleaner/www/framework/Zend/Soap/Client/Common.php on line 51
May 27 12:24:01 localhost httpd: PHP Warning:  SoapServer::SoapServer(http://localhost:5132/soap/index.php?wsdl): failed to open stream: HTTP request failed!  in /usr/mailcleaner/www/framework/Zend/Soap/Server.php on line 762
May 27 12:24:01 localhost httpd: PHP Warning:  SoapServer::SoapServer(): I/O warning : failed to load external entity &quot;http://localhost:5132/soap/index.php?wsdl&quot; in /usr/mailcleaner/www/framework/Zend/Soap/Server.php on line 762
May 27 12:24:01 localhost httpd: PHP Fatal error:  SOAP-ERROR: Parsing WSDL: Couldn't load from 'http://localhost:5132/soap/index.php?wsdl' : failed to load external entity "http://localhost:5132/soap/index.php?wsdl"#012 in /usr/mailcleaner/www/framework/Zend/Soap/Server.php on line 762
May 27 12:24:41 localhost httpd: PHP Warning:  SoapServer::SoapServer(http://localhost:5132/soap/index.php?wsdl): failed to open stream: HTTP request failed!  in /usr/mailcleaner/www/framework/Zend/Soap/Server.php on line 762
May 27 12:24:41 localhost httpd: PHP Warning:  SoapServer::SoapServer(): I/O warning : failed to load external entity &quot;http://localhost:5132/soap/index.php?wsdl&quot; in /usr/mailcleaner/www/framework/Zend/Soap/Server.php on line 762
May 27 12:24:41 localhost httpd: PHP Fatal error:  SOAP-ERROR: Parsing WSDL: Couldn't load from 'http://localhost:5132/soap/index.php?wsdl' : failed to load external entity "http://localhost:5132/soap/index.php?wsdl"#012 in /usr/mailcleaner/www/framework/Zend/Soap/Server.php on line 762
May 27 12:24:42 localhost httpd: PHP Fatal error:  SOAP-ERROR: Parsing WSDL: Couldn't load from 'http://127.0.0.1:5132/soap/index.php?wsdl' : failed to load external entity "http://127.0.0.1:5132/soap/index.php?wsdl"#012 in /usr/mailcleaner/www/framework/Zend/Soap/Client/Common.php on line 51

Can someone provide some information about those errors? Keep in mind, that after disabling the "Enable SSl(HTTPS)" option, the above erros stop.

**Comment by JohnMertz** [comment]
Hello,

Sorry for the long delay. I'm going through all of the open issues right now and cannot replicate this issue. I'm curious if you are still experiencing it?

The logs indicate that requests on the SOAP interface are failing. Given that it happened when you enabled HTTPS, it suggests that HTTP traffic may have begun being blocked. This is not something that should happen because of any actions made by enabling HTTPS. The SOAP interface is defined in:

    /usr/mailcleaner/etc/apache/httpd.conf_template

It is not impacted by SSL arguments; it always just uses regular HTTP (since it is accessed on localhost).

SOAP also runs on the dedicated port 5132, so even if port 80 were to be restricted by other means, it should still be available.

To be able to learn more about this, you would need to investigate the internal access on port 5132.

**Comment by joaomarcosmareto** [comment]
Thanks for replying John.

Sadly we had to switch to another mail gateway system, as we couldm't find any solution for this problem in time.

If this only happened with us, you can close this issue. But only for information, in our tests we installed the appliance available on site and tried to enable the ssl option as I said in first comment.
