### ISSUE TITLE
 reject subject

### ISSUE THREAD

**Issue by ozgursuder** [MailCleaner/MailCleaner#353]
Hello there

Spam e-mails are constantly coming in about the same subject. Is there a way I can block this directly?

header  __AR_SUBJECT_XXX           Subject =~ /Invest in Crypto.Earn 100.000/
score   AR_SUBJ_XXX  		   20.0

I tried as above but it didn't work

**Comment by JohnMertz** [comment]
Hello,

Sorry for the delay. General usage questions are better to be discussed on the forum.mailcleaner.org

SpamAssassin has a general document here:

    https://cwiki.apache.org/confluence/display/spamassassin/WritingRules

The reason your rule did not work is:

    "rules starting with a double underscore are evaluated with no score, and are intended for use in meta rules where you don't want the sub-rules to have a score"

To use the rule on it's own, simply omit the '__' at the start of the rule name. Also note that the rule name needs to match in each section. The way you have written the rule implies that there is a meta rule called 'AR_SUBJ_XXX' which has the sub-rule '__AR_SUBJECT_XXX' as a component, however no meta rule exists and this sub-rule has no associated score (and wouldn't be evaluated with one anyways because of the '__').
