### ISSUE TITLE
Exim spool stage4

### ISSUE THREAD

**Issue by mvldebian** [MailCleaner/MailCleaner#378]
My mailcleaner stopped this morning and when I restart the services it can't start exim stage 4

I'm trying to find the cause, no success

**Comment by mvldebian** [comment]
I gave up trying to restart the stage4 service, and as a last resort I restarted the virtual machine. Then the most serious problem started, the machine was no longer able to boot...

I noticed that when I left the vm without internet, the system managed to go up, giving an error on stage1 but at least it went up.

Now with the system running, when I need to restart the Incoming MTA service I have a completely unusual delay, it takes several minutes to restart.

Does something in the system boot script need to connect to some remote server or download? It had been a long time since I restarted this machine and this behavior of getting stuck at boot took me completely by surprise.

About stage1 and its delay, where can I look for logs that help me understand this delay? the restart was always fast taking just a few seconds, it started behaving like that today...

**Comment by JohnMertz** [comment]
The stage 1 log is:

    tail -f /var/mailcleaner/log/exim_stage1/mainlog

It does not require any external resources to start itself, but there are related scripts that can. Specifically, you could try running the configuration dumper script to see if it finishes quickly:

    /usr/mailcleaner/bin/dump_exim_config.pl 1

This does so DNS requests which would take a long time without network access.

Alternatively, you can try to directly run the daemon startup command using the configuration file that was dumped the last time:

    start-stop-daemon --start --pidfile /var/mailcleaner/run/exim_stage1.pid --exec /opt/exim4/bin/exim -- -C /var/mailcleaner/spool/tmp/exim/exim_stage1.conf -bd -q5m

In all of these examples, simply swapping the '1' for '2' or '4' will work for the other MTAs.

One of these should should give some insight into where the delay is happening.

**Comment by mvldebian** [comment]
Running

/usr/mailcleaner/bin/dump_exim_config.pl 1

It takes 10 to 15 minutes to complete this process;

Does this dump also include the whitelist? I suspect that my whitelist has many domains and may be causing this delay, I'm trying to find out where it's items are dumped from the database.

**Comment by JohnMertz** [comment]
Several database tables and flat files get dumped. The most likely culprit is one of the fields using the 'expand_host_string' function which generates IP range lists from DNS names and other patterns. This feature is discussed here:

https://support.mailcleaner.net/boards/3/topics/94

That article mentions all of the fields in the WebUI, or you can get the same from the following:

Host blacklists which get stored in:

 /var/mailcleaner/spool/tmp/exim/blacklists/hosts

database columns from the mc_config database (connect with `mc_mysql -m mc_config`):

 antispam.trusted_ips
 antispam.html_wl_ips
 mta_config.no_ratelimit_hosts
 mta_config.relay_from_hosts
 mta_config.smtp_conn_access
 mta_config.hosts_require_tls
 mta_config.rbls_ignore_hosts
 mta_config.spf_dmarc_ignore_hosts
 
entries in wwwlists table with types:

 black-ip-dom
 spam-ip-dom
 white-ip-dom
 wh-spamc-ip-dom

and the file:

 /var/mailcleaner/spool/mailcleaner/full_whitelisted_hosts.list

You can include the details in an email to support@mailcleaner.net and I'll be happy to see whether any of your settings confuse this part of the dumper. Mention my name so that I'll be alerted quicker.

**Comment by JohnMertz** [comment]
Regular Anti-Spam whitelists have no impact on Exim and are not dumped. They are only evaluated during filtering inside the SpamHandler module. It is pretty much only settings within the Configuration->SMTP menu that are relevant to the service restart/dumper.

The actual restart script suppresses error output. If you run the `dump_exim_config.pl` script directly (which is the only part of the init script which has a significantly variable runtime), as described above, this will not suppress the output. 

For anything that takes this long, it is probably relevant to one of the Hostlists which get expanded, simplified and then dumped by the GetDNS.pm library. These are the fields that I mentioned in my previous reply. It does include IP and domain whitelists for features like DMARC and SPF checks, but I hope that you don't have so many entries in these field as to cause this problem. These fields are generally only for individual workarounds and if you are using them heavily, you probably have another problem with routing/relaying.

To test my theory that it is one of these fields that is responsible, you can go to the very bottom of the file `/usr/mailcleaner/bin/dump_exim_config.pl` and add the following line to see which field is taking so long:

```
sub expand_host_string
{
    my $string = shift;
    my %args = @_;
    print STDERR time() . ' ' . $args{'dumper'} . "\n";    # ADD THIS
    my $dns = GetDNS->new();
    return $dns->dumper($string,%args);
}
```
Then run it for whichever stage you would like, as previously mentioned. It will print the field that is being dumped when it starts (with a timestamp, so you don't have to sit around and watch). It will not indicate when it finishes each, but everything else in the script wouldn't normally take more than a few seconds, so that is a rounding error. The field that get printed can be searched earlier in the script right alongside a reference to the database row, and the variable in the template that it is replacing. eg. if the slow one appears to be `exim/html_ctrl_wl_hosts`, you could find:

```
$sconfig{'__HTML_CTRL_WL_HOSTS__'} = join(' ; ', expand_host_string($row{'html_wl_ips'},('dumper'=>'exim/html_ctrl_wl_hosts')));
```

This is to replace `__HTML_CTRL_WL_HOSTS__` in the template with the processed content of `html_wl_ips`.  This is in the table `mta_config` which is found when `%row` is first declared earlier in that function.

One or more of these fields is almost definitely the cause of the delay. If the field ends up not actually having a long or complicated list, you can feel free to forward it's contents to us privately at support@mailcleaner.net and I can look for whatever other issues might be occurring.
