### ISSUE TITLE
Problem with SMTP "An error occurred  Application error"

### ISSUE THREAD

**Issue by sajidalifrt** [MailCleaner/MailCleaner#426]
Hi

Getting this error when trying to Access SMTP Settings via the web GUI

An error occurred
Application error

Tried rebooting the server

Need to add AN IP address to allow SMTP Relaying tried editing the EXIM File in /usr/mailcleaner/etc/exim but the file reverts when restarted

![smtp](https://user-images.githubusercontent.com/98099071/150346582-6438d059-4ecc-4ba6-9ff1-20b1f704d8c9.png)

thanks for advice

**Comment by JohnMertz** [comment]
It is very likely that your database has not updated. We recently added a new SMTP setting and if the UI is trying to find a setting that does not exist, this is what I'd expect to see.

First, try fully updating with:

/root/Updater4MC/updater4mc.she

If this does not resolve the issue, look for error when updating the database directly:

/usr/mailcleaner/bin/check_db.pl --update

If this works, but the problem persist, check that the column for this setting does actually exist:

echo 'select block_25_relay from mta_config' | /usr/mailcleaner/bin/mc_mysql -m mc_config

If it does not, the definition file must be failing to update. You'd need to check the status of the Git tree to see if there is something blocking changes.

The overwriting of the config file is normal. Every time services in MailCleaner restart, there is a '_template' (suffix) file which is dumped to replace the existing config file. This pulls all of the relevant settings from the database to build a new file with all of your preferences in place. In the case of Exim, this is actually '_template_4.94' for Stage 1 and 4 since this latest version requires unique settings. To apply a setting directly, you would need to edit the template, but this is strongly discouraged as it would block updates. Since you cannot see the UI, you would be better to update the database directly:

/usr/mailcleaner/bin/mc_mysql -m mc_config

Then get the existing list:

select relay_from_hosts from mta_config where stage = 1;

And update with the new IP, for example (replace with your list and new IP):

update mta_config set relay_from_hosts = '1.1.1.1
2.2.2.2
x.x.x.x' where stage = 1;

**Comment by sajidalifrt** [comment]
Thanks for quick reply. I will update after apply this solution.

**Comment by sajidalifrt** [comment]
Great, it worked.

Thanks again.
