### ISSUE TITLE
ClamAV daemon: critical (not running and required) - EOL of V101 reached?

### ISSUE THREAD

**Issue by nformsven** [MailCleaner/MailCleaner#430]
Hello,
my up-2-date mailcleaner installation hast the following problem: 
`ClamAV daemon: critical (not running and required)`
It seems like Freshclam can't obtain new database updates (main.cld, daily.cld, bytecode.cld). I tried deleting the old databases and also tried deeting the "mirrors.dat" file. But the following messages kept appearing in the Freshclam log:

**Freshclam.log:**
```
[2022-02-28 10:00:12] Starting ClamAV update...
--------------------------------------
ClamAV update process started at Mon Feb 28 10:00:12 2022
WARNING: Your ClamAV installation is OUTDATED!
WARNING: Local version: 0.101.2 Recommended version: 0.103.5
DON'T PANIC! Read https://www.clamav.net/documents/upgrading-clamav
ERROR: Can't download main.cvd from database.clamav.net
Giving up on database.clamav.net...
Update failed. Your network may be down or none of the mirrors listed in /usr/mailcleaner/etc/clamav/freshclam.conf is working. Check https://www.clamav.net/documents/official-mirror-faq for possible reasons.
[2022-02-28 10:00:24] Network error, not able to download data now,retrying later...
[2022-02-28 10:00:24] Done.
```

**Version installed:**
```
root@mailcleaner:/opt/clamav/sbin# dpkg -l |grep mc-clamav
ii  mc-clamav                             0.101.4-1                          amd64        This package includes the specific clamav package used by Mailcleaner
```

Could this be the reason that I am not able to obtain ClamAV database updates?
**EoL vor ClamAV 0.101.4-1 reached?**
https://docs.clamav.net/faq/faq-eol.html#version-support-matrix

**Comment by JohnMertz** [comment]
Hello,

You have correctly identified the issue. We now have a newer version of the package available in the repositories, but we haven't forced an upgrade with Updater4MC yet. This is because in the early testing of the new package, it created some performance issues. It has since been re-compiled and performance seems to be fine, so we will be automatically updating all MailCleaner machines some time this week. If you would like to force it earlier, you should be able to do so with:

```
apt update && apt upgrade -y --force-yes mc-clamav
```

The new packages are still propagating to our CDN, so it may not be found after a single `apt update`. Also note that it depends on a new custom version of `pcre2` which will also be installed silently.

Finally, the inability to start at all should be limited to only machines that have been newly created since this version was deprecated. Machines which already had the freshclam databases will still be able to start but are blocked from getting new updates.

**Comment by JohnMertz** [comment]
ClamAV 103.5 (the latest on the old branch) has now been pushed through Updater4MC. Closing.
