### ISSUE TITLE
Forwarded email rejected

### ISSUE THREAD

**Issue by mvldebian** [MailCleaner/MailCleaner#449]
I have the following scenario, MC as MX and SMTP as mail server.
When I configure an account to be copied to an email external to the organization, the MC returns saying 550 relay not permitted.
How to make it send copies to domains not allowed in the relay? example @gmail @hotmail. etc

**Comment by JohnMertz** [comment]
Hello,

First, for community support, we recommend inquiring on [our forums](https://forum.mailcleaner.org/). Issues on GitHub should be limited to feature requests and software bugs.

That said, I'll try to comment based on what I understand from your question:
- Your MX records point to an MC machine.
- MC then forwards to another SMTP server (all mail servers are SMTP; I assume you just mean a typical terminating server like Postfix, Exim, Exchange, etc.). I'll refer to this as 'Back-End'.
- After the message arrives at the Back-End, you have some number of those messages forwarded to another machine.
- Some of those message are rejects by MC because the sending domain is not allowed to relay to them.

This implies that you also use MC as an outgoing relay (smarthost). The basic mechanics are that MC will only forward to domains in the recipient table (domains that are configured and enabled in Configuration->Domains), unless the source is defined to allow external relaying. The latter can be done either:

- by allowing one of the recipient domains to do authenticated relaying (Configuration->Domains->[select domain]->Outgoing relay).

-  by allowing the source IP (Configuration->SMTP->Connection control->Allow external relaying for these hosts). This will also only allow relaying from the configured domains unless you enable "Allow relaying from unknown domains".

Note that you MUST have the sender address changed when the message is forwarded. If you try to 'redirect' without changing the sender address MailCleaner will not allow it to be relayed unless the second relaying method and "unknown domain" setting are selected. Even if you do that, the messages are almost definitely going to get blocked by the new recipient since you will fail SPF and other legitimacy checks. It would also get your MC machine blocked by an RBL for this spoofing.

Based on what you are explaining, it sounds like that last point might be the issue. It is unclear whether you are forwarding **to** the freemail addresses or messages that were **from** those domains. Regardless, when your Back-End tries to connect to MC to send the forwarded copy, it must be from an approved relay and domain.
