### ISSUE TITLE
Status only "- nan" / User Spam access not working

### ISSUE THREAD

**Issue by torra-it** [MailCleaner/MailCleaner#461]
After removing a slave node, I now don't have any values in "Status" except the current. It's only displayed "- nan" when I select "Show more". The second problem is that the generated link in the Spam notification e-mail doesn't work anymore. The page is "Not found" for the users when opening something like "https://<mailserver>/?d=759e...067d&p=u" (I shortened the link replacing ...).
Everything else works fine. I can release a "wrong" spam as administrator.

Maybe there is an issue with the master database. I'm not sure that the mailcleaner is using the right database. But that's only a thought because I saw a try to connect to the missing cluster (that did not were the master).

Is the status generated feshly when opening it, or does some jobs not work properly?
What can I check and where?

Thanks in advance!

**Comment by JohnMertz** [comment]
Cleaning up old issue...

If you remove the Slave node, it needs to be removed from the master as well `/usr/mailcleaner/scripts/configuration/slaves.pl`. If the slave is still a member of the cluster as far as the Master is aware, it will try to fetch the stats from the removed machine. This generally causes the whole interface to lock up while it waits for a response.

All information in Monitoring->Status is fetched upon request using the SOAP API, some from cached data (eg. the graphs), and others from live system calls (eg. queue sizes).

Spams are store on the node that filtered them, so if you remove that node from the cluster and then try to use the release link, it will give you NOTFOUND, since that machine is no longer accessible to provide the message.

I'm not sure that I understand all of the questions here, but I suspect that it was all related to the node being removed.

Please open another issues if you are still having problems.
