### ISSUE TITLE
Seems mailcleaner do not permit tls 1.2 ?

### ISSUE THREAD

**Issue by troublestarter** [MailCleaner/MailCleaner#530]
Hi

Here the issue in smtp logs :

2023-07-04 14:50:14 TLS error on connection from xpmail-185.axalone.com [213.41.74.185] (SSL_accept): (TLSv1.2)
2023-07-04 14:50:15 TLS error on connection from xpmail-185.axalone.com [213.41.74.185] (SSL_accept): (TLSv1.2)

Is it possible to modify the Accepted ciphers ? Maybe an issue with SSL library ?
Here my actual accepted ciphers : 

ALL:!aNULL:!ADH:!eNULL:!LOW:!EXP:RC4+RSA:+HIGH:+MEDIUM:!SSLv2

**Comment by JohnMertz** [comment]
Hello,

TLS1.2 is supported with the latest available Exim (4.96), however, it is possible that the full suite of ciphers is not, causing a mismatch with the remote machine. I looked in my log for errors and I saw similar errors occasionally, but in this example the very next line was successful:

```
2023-07-05 14:30:39 TLS error on connection from hostname1 [x.x.x.x] (SSL_accept): (TLSv1.2)
2023-07-05 14:30:57 1qH1eq-0003G4-2u <= sender@domain.com H=hostname2 [y.y.y.y] P=esmtps X=TLS1.2:ECDHE-RSA-AES256-GCM-SHA384:256 CV=no
 S=73025 DKIM=domain.com id=ID T="Subject"
```

The error does really indicate what the problem is. If I use the site checktls.com and view the details for the sending host in your example, and my MailCleaner (Exim 4.96, with the same cipher string as yours), both show:

```
Connection converted to SSL
SSLVersion in use: TLSv1_2
Cipher in use: ECDHE-RSA-AES256-GCM-SHA384
```

This indicates that they do have a common, best possible cipher. The machine that failed for me also shows the same. Furthermore, just 1 minute after my failure, the same machine is able to successfully send using the above cipher.

So, in my case, it appears to be a transient issue with the actual TLS negotiation. I'm afraid that I don't know enough about that. It would really be a question for Exim.

So, I can suggest that you make sure that the machine is up-to-date with Exim 4.96, and check to see if the same hosts later succeed. If there is still an issue you can try asking the Exim mailing list.

**Comment by troublestarter** [comment]
Thanks for the reply.

-> These host never succeed to send mail to us.
-> Exim package installed is 4.96

I will try to find informations with exim.

Thanks you.

**Comment by JohnMertz** [comment]
It is possible that one today's commits (#543) would have fixed this issue. This enhancement forces the sending of the client certificate for outbound messages. Some very strict servers (generally the same ones that would require >=TLSv1.2), will reject sessions which don't have a verified client certificate.

If you are still having the issue, please ensure that the installed certificate (Configuration->SMTP->TLS/SSL) includes the hostname of your machine(s) as a subject, then run `/root/Updater4MC/updater4mc.sh`, and verify if the issues is resolved.

**Comment by troublestarter** [comment]
I will test this soon
