### ISSUE TITLE
Can't receive some mail with SSL routines:SSL3_READ_BYTES:sslv3 alert certificate unknown

### ISSUE THREAD

**Issue by troublestarter** [MailCleaner/MailCleaner#557]
Hi

I Can't receive some mail with SSL routines:SSL3_READ_BYTES:sslv3 alert certificate unknown

We have many logs like this 

2023-10-11 09:59:34 TLS error on connection from ip1.tpm01.net [81.93.29.68] (SSL_accept): error:14094416:SSL routines:SSL3_READ_BYTES:sslv3 alert certificate unknown

Have you an idea of this kin of issues ?
A test from this MTA to gmail succeed.

See also here : https://forum.mailcleaner.org/viewtopic.php?f=2&t=3143&p=12967&hilit=SSL3_READ_BYTES#p12967

Thanks you !

**Comment by JohnMertz** [comment]
Typically this means that your certificate cannot be verified for one of a number of reasons:

- You have an incomplete chain of certificates back to the trusted root CA.
- Your certificate cannot be verified (eg. the hostname of your machine is not included as a subject of the certificate).
- Your certificate is expired.
- etc.

I like to use [CheckTLS](https://checktls.com/TestReceiver) to easily check for TLS errors. Did you update your certificate recently? Or did it expire recently? I can check a few things for you, but would need the hostname of the machine(s). You can email it to support@mailcleaner.net if you don't want to post it here.

**Comment by troublestarter** [comment]
Thanks for the tip.


  | Certificate #1 of 1 (sent by MX):
-- | --
  |   | Cert VALIDATION ERROR(S): self signed certificate
  |   | So email is encrypted but the recipient domain is not verified
  |   | Cert Hostname DOES NOT VERIFY (mail-protection.xx-xxxx.info != mailcleaner)
  |   | So email is encrypted but the host is not verified

Possible to use letsencrypt for this ?
Have you please a method for this ?

Thanks

**Comment by JohnMertz** [comment]
Hello,

You can certainly use a Let's Encrypt certificate. You just need to paste the 'fullchain' into the certificate box from Configuration->SMTP->TLS/SSL, and the private key into the other box. Note that if you want to use this certificate for HTTPS, you can also do that at Configuration->Services->Web Interface, but note that there is a third box where you need to separate the chain certificates (all but the first in the 'fullchain' into the the third box, on only the local certificate in the first. 

I personally use a Let's Encrypt certificate and have a cron task to pull the fullchain.pem and privkey.pem from my main web server machine, then run this this script to automatically install it for both HTTPS and SMTP:

```bash
#!/bin/bash

usage() {
	echo "Usage: $0 public_chain private_key [-R]"
	echo "	-R  Don't restart services"
	exit;
}

SRCDIR=`grep 'SRCDIR' /etc/mailcleaner.conf | cut -d ' ' -f3`

RESTART=1
if [ ! $1 ] || [ ! $2 ]; then
	echo "Missing argument"
	usage
elif [[ ! -r $1 ]]; then
	echo "Cannot read $1"
	usage
elif [[ ! -r $2 ]]; then
	echo "Cannot read $2"
	usage
fi
if [ $3 ]; then
	if [[ $3 -eq '-R' ]]; then
		echo "Not restarting"
		RESTART=0
	else
		echo "Invaild option '$3'"
		usage
	fi
fi

CERT=`cat $1 | grep -m 1 -B 1000 'END CERTIFICATE'`
COUNT=`cat $1 | grep -c 'END CERTIFICATE'`
let "COUNT--"

if [ $COUNT ]; then
	CHAIN=`tac $1 | grep -m $COUNT -B 1000 'BEGIN CERTIFICATE' | tac`
else
	CHAIN=''
fi

cat << EOF | ${SRCDIR}/bin/mc_mysql -m mc_config
UPDATE mta_config set tls_certificate_data = '`cat $1`';
EOF

cat << EOF | ${SRCDIR}/bin/mc_mysql -m mc_config
UPDATE mta_config set tls_certificate_key = '`cat $2`';
EOF

if [[ $RESTART == 1 ]]; then
	for i in 4 2 1; do ${SRCDIR}/etc/init.d/exim_stage$i restart; done
fi

cat << EOF | ${SRCDIR}/bin/mc_mysql -m mc_config
UPDATE httpd_config set tls_certificate_data = '`echo -e "$CERT"`';
EOF

cat << EOF | ${SRCDIR}/bin/mc_mysql -m mc_config
UPDATE httpd_config set tls_certificate_chain = '`echo -e "$CHAIN"`';
EOF

cat << EOF | ${SRCDIR}/bin/mc_mysql -m mc_config
UPDATE httpd_config set tls_certificate_key = '`cat $2`';
EOF

if [[ $RESTART == 1 ]]; then
	${SRCDIR}/etc/init.d/apache restart
fi
```

You just need to make sure that you generate or expand the Let's Encrypt certificate to include your mailcleaner hostname.

The '!= mailcleaner' it is objecting to should the hostname that is declared in the self-signed certificate. As just mentioned, in your Let's Encrypt certificate this will need to include the public hostname of the machine in the subject list.

Also note that some very strict senders will also want your HELO name to match. When the Exim configuration dumper runs, it tries to source this from a few places, most importantly as the 'HELONAME' in `/etc/mailcleaner.conf`.

**Comment by troublestarter** [comment]
Thanks for the full documented reply.

I'm thinking about this, my mailcleaner web is served by an haproxy, so https is good, but the two MX point directly to the mailcleaner hosts with a hostname different than the mailcleaner webserver...

So i can't catch the direct request to the IP of mailcleaner use by the MX.

I will try to see if your script can help me.

Thanks you.

**Comment by troublestarter** [comment]
I wrote you an email so that you can see the privatekey.
The fullchain is used for the first box.

**Comment by JohnMertz** [comment]
Interesting... I've just set up a new PC and locked myself out of the support mailbox until tomorrow, so I'll have to check your email then (otherwise you can send it directly to my mailbox: john.mertz@mailcleaner.net).

The function which checks the private key is in the file `/usr/mailcleaner/www/guis/admin/application/models/PKI.php:118`, which simply passes the input to the openssl command `openssl RSA -check -in tmpfile` where the `tmpfile` is the key that you input. If that check fails, it seems it should provide the error 'invalidPrivateKey' (`/usr/mailcleaner/www/guis/admin/application/library/Validate/PKIPrivateKey.php:28`). Instead you are getting the generic error for a bad form submission (this may be a misunderstanding on my end, since the code that raises the error message is deep in the Zend framework which I don't really look at).

I confirmed that the form does work on my machine, so it suggest that it is an issue with your key. I would first suggest running the openssl command above against a file with your key. If it comes back as valid, then compare to make sure that the key matches the certificate:

```
openssl x509 -noout -modulus -in CERTIFICATE.crt | openssl md5
openssl rsa -noout -modulus -in PRIVATEKEY.key | openssl md5
```

If both of these look fine, you should be able to apply the certificate with my script. There should be no harm in enabling HTTPS even if it is behind a proxy (my machine is behind Nginx and the proxy still works as expected). Otherwise, you could comment out the lines related to `mta_config` and `apache`. The script does not have any of the checks that exist in the web, so it will apply the cert and key even if they are entirely invalid (in which case the relevant services will probably fail to start, so you should save a copy of the self-signed cert to restore partial functionality). Once applied with the script you can use CheckTLS again to see if it resolved the issue.

Once again, I'll check for your email after my morning meeting and will let you know if I can spot a problem.

**Comment by troublestarter** [comment]
I have sent you the file on your email.
I also tried you suggestion with lci commands :

![image](https://github.com/MailCleaner/MailCleaner/assets/6012203/6280070a-cb7a-4d16-8b3f-fe30b7794a65)

**Comment by troublestarter** [comment]
Seems just because now priv key are generated in ECDSA format.

https://community.letsencrypt.org/t/ecdsa-certificates-by-default-and-other-upcoming-changes-in-certbot-2-0/177013

**Comment by troublestarter** [comment]
I have to use : --key-type rsa to have RSA format working

**Comment by JohnMertz** [comment]
ECSDA will be targeted for the next major release https://github.com/MailCleaner/MailCleaner-Next, but will probably never be added to the Jessie release.

**Comment by troublestarter** [comment]
Thanks for your feedback.
So we can actually do the cert managment with CLI so it is not urgent.
We will see how to do the upgrade process...
