### ISSUE TITLE
Spam blocklist SORBS shuts down

### ISSUE THREAD

**Issue by Brauadler** [MailCleaner/MailCleaner#614]
> The Spam and Open Relay Blocking System (SORBS) was decommissioned on June 5, 2024, and the service no longer contains reputation data

I found this information after looking for changes in the Spamassassin project on Github. All rules related to SORBS have been removed from their project. Should this now obsolete list also be removed in Mailcleaner? 

Since this blocklist is built into various MC anti-spam modules as well as the SMTP checks, I didn't want to push any changes myself. In addition, there should also be rules in the `20_dnsbl_test.cf` file that are not updated directly with the Mailcleaner/Mailcleaner project.

**Comment by JohnMertz** [comment]
I saw this and was just working on an update to remove it from the list of enabled RBLs for SMTP, PreRBL and SpamC, and remove the config file from `etc/rbls/SORBS.cf` so that it does not appear in the WebUI in order to re-enable it.

When SORBS is not in the the column `antispam.sa_rbls` (of `mc_config` DB), the `share/spamassassin/92_mc_dnsbl_disabled.cf_template` will be dumped with all of the SORBS scores overridden to 0. This disables the rules, so they will not be evaluated and the DNS requests should not be made. This means that it should not be necessary to actually modify the upstream `20_dnsbl_test.cf` file.

If someone manually added SORBS back to any of the RBL lists via SQL, it would fail for SMTP and PreRBL, since the config will no longer exists, but the SA rules would run (and also fail) since it is dependent on the SA rules file, not our config. But we cannot control users manually breaking things.

I should have this update out soon.

**Comment by JohnMertz** [comment]
RBL config file is removed in the last commit and will be removed if configured for any of the RBL phases in the latest Updater4MC script.
